spring:
    application:
        name: zfly-cloud-zuul
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 0
        host: youjia.redis.address
        port: 6379
        password:
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
        timeout: 2000


server:
    port: 8865 #启动端口
#
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  routes:
    zfly-order:
      path: /order/**
      serviceId: zfly-order
    zfly-user:
      path: /user/**
      serviceId: zfly-user
#可以配置多个serviceId

ribbon:
  httpclient:
    enabled: true
#  okhttp:
#    enabled: true
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  #MaxAutoRetries: 1
  #MaxAutoRetriesNextServer: 2
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: true

#由于springcloud默认是开启的重试机制，开启次机制以后会导致当springcloud请求超时时会重复调用业务模块，
#从而会引发数据混乱，因此建议将其禁用。对于网络模块超时等故障问题建议使用hytrix方式。

hystrix:
  threadpool:
    default:
      coreSize: 200 ##并发执行的最大线程数，默认10
      maxQueueSize: 2000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 70000
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 500
